[tool.poetry]
name = "course4"
version = "0.1.0"
description = ""
authors = ["zahar92 <mail-runet@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
